### ISSUE TITLE
.no-js getting triggered. 

### ISSUE THREAD

**Issue by rgfx** [tdtgit/tdt-lazyload#13]
I  have javascript running. When deleting this line in the CSS I got it to work. 

    .no-js img.lazyload {
    	display: none;
    }

I disabled all my js and css and plugins just to make sure it wasn't me. No console errors working locally. 

But still, I've used Lazysizes for years on everything but my WordPress sites. Certainly the best lazy load script. Their plugin never seemed to work right for me. 

Good work.

**Comment by tdtgit** [comment]
Can you show me your WordPress sites to check it?
